# Generated by Django 5.1.2 on 2024-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='acknowledge_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Principiante'), ('Intermediate', 'Intermedio'), ('Advanced', 'Avanzado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Estudiante'), ('Teacher', 'Profesor')], max_length=10, null=True),
        ),
    ]
